'use client';

import { useState, useEffect } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Eye, Copy, Download, X } from 'lucide-react';
import { CodeEditor } from '@/components/code-editor';
import { HTMLPreview } from '@/components/html-preview';
import { fetchChatFiles, fetchFile, updateFile } from '@/lib/api';
import type { FileItem } from '@/lib/types';
import { FileLoading } from '@/components/ui/loading';

interface FilePanelProps {
  chatId: string;
}

export function FilePanel({ chatId }: FilePanelProps) {
  const [files, setFiles] = useState<FileItem[]>([]);
  const [selectedFile, setSelectedFile] = useState<FileItem | null>(null);
  const [fileContent, setFileContent] = useState<string>('');
  const [showPreview, setShowPreview] = useState(false);
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<string>('');

  useEffect(() => {
    if (chatId) {
      loadFiles();
    }
  }, [chatId]);

  const loadFiles = async () => {
    try {
      const filesData = await fetchChatFiles(chatId);
      setFiles(filesData);
      if (filesData.length > 0 && !selectedFile) {
        const firstFile = filesData[0];
        setSelectedFile(firstFile);
        setActiveTab(firstFile.id);
        loadFile(firstFile.id);
      }
    } catch (error) {
      console.error('Failed to load files:', error);
    }
  };

  const loadFile = async (fileId: string) => {
    setLoading(true);
    try {
      const fileData = await fetchFile(fileId);
      setFileContent(fileData.content || '');
    } catch (error) {
      console.error('Failed to load file:', error);
    }
    setLoading(false);
  };

  const handleFileSelect = (file: FileItem) => {
    setSelectedFile(file);
    setActiveTab(file.id);
    loadFile(file.id);
    setShowPreview(false);
  };

  const handleContentChange = async (newContent: string) => {
    setFileContent(newContent);
    if (selectedFile) {
      try {
        await updateFile(selectedFile.id, newContent);
      } catch (error) {
        console.error('Failed to update file:', error);
      }
    }
  };

  const handlePreviewToggle = () => {
    setShowPreview(!showPreview);
  };

  const handleCopyContent = () => {
    navigator.clipboard.writeText(fileContent);
  };

  const handleDownload = () => {
    if (selectedFile) {
      const blob = new Blob([fileContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = selectedFile.filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  if (files.length === 0) {
    return (
      <div className="flex items-center justify-center h-full bg-gray-50">
        <div className="text-center text-gray-500">
          <div className="text-lg mb-2">No files yet</div>
          <div className="text-sm">Files will appear here when generated by the chat</div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-white">
      {/* Header */}
      <div className="flex items-center justify-between p-3 border-b bg-gray-50">
        <h3 className="font-medium text-sm">Untitled</h3>
        <div className="flex items-center gap-1">
          <Button 
            variant="ghost" 
            size="sm"
            onClick={handlePreviewToggle}
            className={showPreview ? 'bg-gray-200' : ''}
          >
            <Eye className="h-4 w-4" />
            Preview
          </Button>
          <Button variant="ghost" size="sm" onClick={handleCopyContent}>
            <Copy className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="sm" onClick={handleDownload}>
            <Download className="h-4 w-4" />
          </Button>
        </div>
      </div>

      {/* File Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col">
        <TabsList className="w-full justify-start rounded-none border-b bg-transparent p-0">
          {files.map((file) => (
            <TabsTrigger
              key={file.id}
              value={file.id}
              onClick={() => handleFileSelect(file)}
              className="flex items-center gap-2 rounded-none border-r data-[state=active]:bg-white data-[state=active]:border-b-white relative px-4 py-2"
            >
              <span className="text-sm">{file.filename}</span>
              <button className="ml-2 opacity-0 group-hover:opacity-100 hover:bg-gray-200 rounded p-0.5">
                <X className="h-3 w-3" />
              </button>
            </TabsTrigger>
          ))}
        </TabsList>

        {files.map((file) => (
          <TabsContent key={file.id} value={file.id} className="flex-1 m-0">
            {loading ? (
              <div className="flex items-center justify-center h-full">
                <FileLoading />
              </div>
            ) : showPreview && file.filename.endsWith('.html') ? (
              <HTMLPreview htmlContent={fileContent} isVisible={true} />
            ) : (
              <CodeEditor
                fileId={selectedFile?.id}
                initialContent={fileContent}
                onContentChange={handleContentChange}
              />
            )}
          </TabsContent>
        ))}
      </Tabs>
    </div>
  );
}